[tool.poetry]
package-mode = false
name = "tket-docs"
version = "0.1.0"
description = "prototype docs build for tket online content"
authors = ["CalMacCQ <93673602+CalMacCQ@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytket = {extras = ["zx"], version = "1.25"}
pytket-qiskit = "^0.48.0"
pytket-cirq = "^0.34.0"
quimb = "1.7.3"
sphinx-book-theme = "^1.1.2"
ablog = "^0.11.6"
Sphinx = "^7.2.6"
jupyter-sphinx = "^0.5.3"
sphinx-copybutton = "^0.5.2"
ipyparallel = "^8.6.1"
qiskit-algorithms = "0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
