name: check manual

on:
  schedule:
    # 03:00 every weekday morning
    - cron: '0 3 * * 1-5'

jobs:
  check:
    name: check manual
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install python requirements for manual
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install -r requirements.txt
        python -m pip install sphinx sphinx_rtd_theme
        python -m pip install --pre git+git://github.com/willsimmons1465/jupyter-sphinx.git@issue-140#egg=jupyter-sphinx
    - name: install graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: build manual
      run: |
        cd manual/
        sed "s/REQUIREMENTS/$(sed -e 's/[\&/]/\\&/g' -e 's/$/\\n/' ../requirements.txt | tr -d '\n')/" index-rst-template > index.rst
        sphinx-build -b html . build 1>out.txt 2>err.txt
        echo "stdout:"
        cat out.txt
        echo "stderr:"
        cat err.txt
        if [[ -s err.txt ]] ; then exit 1 ; fi
