name: check examples

on:
  schedule:
    # 04:00 every weekday morning
    - cron: '0 4 * * 1-5'

jobs:
  check:
    name: check examples
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install python requirements for notebooks
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install -r requirements.txt
        python -m pip install jupyter openfermion plotly
        python -m pip install docker p2j
    - name: install dotnet SDK and iqsharp
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
        sudo apt-get install dotnet-sdk-3.1
        echo "~/.dotnet/tools" >> $GITHUB_PATH
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: pull docker images
      run: |
        docker pull rigetti/quilc
        docker pull rigetti/qvm
    - name: test example notebooks
      run: |
        cd examples
        ./check-examples
