name: check examples

on:
  pull_request:
    branches:
      - main
  schedule:
    # 04:00 every Saturday morning
    - cron: '0 4 * * 6'

jobs:

  changes:
    runs-on: ubuntu-20.04
    outputs:
      examples: ${{ steps.filter.outputs.examples }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          examples:
            - 'examples/**'

  check:
    name: check examples
    needs: changes
    if: github.event_name == 'schedule' || needs.changes.outputs.examples == 'true' || github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: install python requirements for notebooks
      run: |
        # if version are updated, update the version in the build-manual file
        # and the requirements.txt, too.
        # this duplication is currently necessary because of an issue with the pyjwt
        # version required from qcs-api-client < 0.21.0
        python -m pip install --upgrade pip
        python -m pip install wheel
        ./install-requirements.sh
        python -m pip install -c constraints.txt jupyter openfermion plotly
        python -m pip install docker p2j pytest
    - name: install dotnet SDK and iqsharp
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
        sudo apt-get install dotnet-sdk-3.1
        echo "~/.dotnet/tools" >> $GITHUB_PATH
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: pull docker images
      run: |
        docker pull rigetti/quilc
        docker pull rigetti/qvm
    - name: test example notebooks
      run: |
        cd examples
        ./check-examples
