name: check docs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # 04:00 every weekday morning
    - cron: '0 4 * * 1-5'

jobs:
  check:
    name: check docs
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install python requirements for manual
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install -r requirements.txt
        python -m pip install sphinx sphinx_rtd_theme
        python -m pip install --pre git+git://github.com/willsimmons1465/jupyter-sphinx.git@issue-140#egg=jupyter-sphinx
    - name: install graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: build manual
      run: |
        cd manual/
        sed "s/REQUIREMENTS/$(sed -e 's/[\&/]/\\&/g' -e 's/$/\\n/' ../requirements.txt | tr -d '\n')/" index-rst-template > index.rst
        sphinx-build -b html . build 1>out.txt 2>err.txt
        cat out.txt err.txt
        if [[ -s err.txt ]] ; then exit 1 ; fi
    - name: install additional python prerequisites for notebooks and tests
      run: |
        python -m pip install jupyter openfermion
    - name: install dotnet SDK and iqsharp
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
        sudo apt-get install dotnet-sdk-3.1
        echo "~/.dotnet/tools" >> $GITHUB_PATH
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: test example notebooks
      if: github.event_name == 'schedule'
      run: |
        # Test all the notebooks that we can on the CI
        python -m pip install docker p2j plotly
        docker pull rigetti/quilc
        docker pull rigetti/qvm
        cd examples
        ./check-examples
