name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        cd pytket-examples-book
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        cd .. 
        jupyter-book build pytket-examples-book

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./pytket-examples-book/_build/html
